{
 "title": "Node.js Observability Dashboard",
 "tags": [
  "nodejs",
  "prometheus"
 ],
 "panels": [
  {
   "title": "CPU do Node.js (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "Node.js CPU (%)"
    }
   ]
  },
  {
   "title": "Uso de Memória do Node.js",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS Memory" }
   ]
  },
  {
   "title": "Requisições por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Request/s"
    }
   ]
  },
  {
   "title": "Total de Requisições HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "File Descriptors do Node.js",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(process_open_fds[1m])", "legendFormat": "File Descriptors" }
   ]
  },
  {
   "title": "Atraso do Event Loop (Latência)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "Event Loop Lag" }
   ]
  }
 ]
}